CREATE TABLE IF NOT EXISTS tasks (
    id TEXT PRIMARY KEY,
    use_case VARCHAR(100) NOT NULL,
    data TEXT NOT NULL, 
    status VARCHAR(50) NOT NULL,
    error_message TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);